#!/usr/bin/ruby
# Hello world ruby program
#puts "Hello world"


#puts "Enter first number:"
#num= gets.to_i

#puts "Enter last number:"
#last= gets.to_i

#while(num<=last)
  #prime_flag=true

  #x=2
 # while ( x <= num/2 )
   # if( num%2 == 0 )
      #prime_flag= false
     # break
    #end
    #x +=1
  #end

  #if prime_flag
    #puts "A prime number is: " + num.to_s
  #end
  #num += 1
#end

puts "Enter two points (x1,y1) and (x2,y2):"

x1=gets.to_i
x2=gets.to_i
y1=gets.to_i
y2=gets.to_i

case
  when(x1==x2)
    puts "Line connect two points is Vertical."
  when(y1==y2)
    puts "Line connect two points is horizontal."
  when((y2>y1) and (x2>x1))
    puts "Slope is positive."
  else
    puts "slope is nagetive."
end

